# available test modules for easier config

class Mods:
    Telephony = 'Telephony'
    Message = 'Message'
    Browser = 'Browser'
    Store = 'Store'
    Pim = 'Pim'
    Media = 'Media'
    Tasking = 'Tasking'
    Wifi = 'Wifi'
    Airplane = 'Airplane'
    Lock = 'Lock'
    Bt = 'Bt'
    Fm = 'Fm'
    Video = 'Video'
    LockScreen = 'LockScreen'
    File = 'File'
    Music = 'Music'
    Navigation = 'Navigation'
    Recorder = 'Recorder'
    Email = 'Email'
    Maps = 'Maps'
    Camera = 'Camera'
    Blackberryapp = 'Blackberryapp'
    Gallery = 'Gallery'
    Gmail = 'Gmail'
    Gps = 'Gps'
    Nfc = 'Nfc'
    Lockscreen = 'Lockscreen'
    Dualsim = 'Dualsim'
    statusbar = 'statusbar'
    Wifihotspot = 'Wifihotspot'
    Launcher = 'Launcher'